### ISSUE TITLE
Readme.md recording link broken

### ISSUE THREAD

**Issue by Lichtlos** [FSecureLABS/Jamf-Attack-Toolkit#1]
Hi,

the youtube recording link is private thus the video unavailable.

Looking forward to seeing it.

stay safe

**Comment by rookuu** [comment]
Hey!

The video has been made private by the conference organisers, we're just waiting to receive a copy to share. I'll update the post and this issue when we receive it. Apologies!

Thanks, and you too.

**Comment by jaredgaut** [comment]
Came here to say the same thing. Thanks for the update.

**Comment by rookuu** [comment]
Thanks both! We're back up on the video now, it can be found at the same link: https://www.youtube.com/watch?v=ZDJsag2Za8w&feature=youtu.be&t=16737.

I'll close the issue.
